import { useContext } from 'react';
import SettlementSummary from '../components/settlement/SettlementSummary';
import SettlementTable from '../components/settlement/SettlementTable';
import { AppContext } from '../context/AppContext';
import { formatDateTime } from '../utils/dateUtils';
import useAuth from '../hooks/useAuth';

const SettlementPage = () => {
  const { settlements, setSettlements, selectedGroupId, setTripLocked, tripLocked, refreshHistory, addHistoryEvent } = useContext(AppContext);
  const { user } = useAuth();

  // 1. Separate Debts into Sectional Lists
  const youOwe = settlements.filter(s => String(s.fromUserId) === String(user?.userId));
  const owedToYou = settlements.filter(s => String(s.toUserId) === String(user?.userId));

  const markPaid = async (settlement) => {
    if (!settlement || !selectedGroupId) return;

    try {
        const { settlementService } = await import('../services/settlementService');
        
        await settlementService.settlePayment({
            groupId: selectedGroupId,
            fromUserId: settlement.fromUserId,
            toUserId: settlement.toUserId,
            amount: settlement.amount
        });

        // Force a global re-sync to remove the settled row and update History
        refreshHistory();
        
        // Manual local update to allow immediate receipt download before the next sync
        setSettlements(prev => prev.map(item => 
            item.fromUserId === settlement.fromUserId && item.toUserId === settlement.toUserId
            ? { ...item, status: 'PAID', paidAt: new Date().toISOString() } 
            : item
        ));
        
    } catch (err) {
        console.error("Settlement failed", err);
        alert("Failed to record settlement. Please check your connection.");
    }
  };

  const lockTrip = async () => {
    if (!selectedGroupId) return;
    try {
        const { groupService } = await import('../services/groupService');
        await groupService.lockGroup(selectedGroupId);
        setTripLocked(true);
        addHistoryEvent('Trip Locked', 'All modifications for this group are now disabled.');
    } catch (err) {
        console.error("Failed to lock trip", err);
    }
  };

  const downloadReceipt = (settlement) => {
    const paidOn = settlement.paidAt ? formatDateTime(settlement.paidAt) : 'Not Available';
    const amountStr = Number(settlement.amount).toFixed(2);
    const content = [
      'Team Expense Management System',
      'Debt Settlement Receipt',
      '------------------------------',
      `From: ${settlement.fromUserName || settlement.from}`,
      `To: ${settlement.toUserName || settlement.to}`,
      `Amount: Rs. ${amountStr}`,
      `Status: PAID`,
      `Paid On: ${paidOn}`,
      '------------------------------',
      `Generated At: ${formatDateTime(new Date().toISOString())}`,
      `Generated By: ${user?.name || 'Authorized User'}`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `receipt-${settlement.fromUserName}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    addHistoryEvent('Receipt Generated', `Downloaded proof of payment for Rs. ${amountStr}`);
  };

  const isFullySettled = settlements.length === 0;

  return (
    <div className="stack-gap-lg">
      <div className="page-header">
        <h1>Settlement Board</h1>
        <button 
            className="btn btn-primary" 
            disabled={tripLocked || settlements.filter(s => s.status !== 'PAID').length > 0 || !selectedGroupId} 
            onClick={lockTrip}
        >
          {tripLocked ? 'Trip Locked' : 'Finalize & Lock Trip'}
        </button>
      </div>

      {isFullySettled ? (
         <div className="empty-state">
            <p>🎉 All settled up in this group! No pending debts found.</p>
         </div>
      ) : (
        <div className="settlement-layout">
            <SettlementSummary rows={settlements} tripLocked={tripLocked} />
            
            <div className="stack-gap-lg">
                <section className="settlement-section">
                    <h3 className="section-title">📉 You Owe (Debts to Clear)</h3>
                    <SettlementTable
                        rows={youOwe}
                        onMarkPaid={markPaid}
                        onDownloadReceipt={downloadReceipt}
                        disabled={tripLocked}
                        isOwner={true}
                    />
                </section>

                <section className="settlement-section">
                    <h3 className="section-title">📈 Owed to You (Receivables)</h3>
                    <SettlementTable
                        rows={owedToYou}
                        onMarkPaid={null} // Read-only for creditor
                        onDownloadReceipt={downloadReceipt}
                        disabled={tripLocked}
                        isOwner={false}
                    />
                </section>
            </div>
        </div>
      )}
    </div>
  );
};

export default SettlementPage;
