import { useContext } from 'react';
import SettlementSummary from '../components/settlement/SettlementSummary';
import SettlementTable from '../components/settlement/SettlementTable';
import { AppContext } from '../context/AppContext';
import { formatDateTime } from '../utils/dateUtils';
import useAuth from '../hooks/useAuth';

const SettlementPage = () => {
  const { settlements, setSettlements, selectedGroupId, setTripLocked, tripLocked, addHistoryEvent } = useContext(AppContext);
  const { user } = useAuth();

  const markPaid = (index) => {
    // Optimized for the DTO index since we don't have stable settlement IDs on-the-fly
    setSettlements((prev) =>
      prev.map((item, i) => (i === index ? { ...item, status: 'PAID', paidAt: new Date().toISOString() } : item))
    );
    addHistoryEvent('Settlement Marked Paid', `Manually marked a settlement row as paid.`);
  };

  const lockTrip = async () => {
    if (!selectedGroupId) return;
    try {
        const { groupService } = await import('../services/groupService');
        await groupService.lockGroup(selectedGroupId);
        setTripLocked(true);
        addHistoryEvent('Trip Locked', 'All modifications for this group are now disabled.');
    } catch (err) {
        console.error("Failed to lock trip", err);
    }
  };

  const downloadReceipt = (settlement) => {
    const paidOn = settlement.paidAt ? formatDateTime(settlement.paidAt) : 'Not Available';
    const amountStr = Number(settlement.amount).toFixed(2);
    const generatedAt = formatDateTime(new Date().toISOString());
    const content = [
      'Team Expense Management System',
      'Debt Settlement Receipt',
      '------------------------------',
      `From: ${settlement.fromUserName || settlement.from}`,
      `To: ${settlement.toUserName || settlement.to}`,
      `Amount: Rs. ${amountStr}`,
      `Status: PAID`,
      `Paid On: ${paidOn}`,
      `Generated At: ${generatedAt}`,
      `Generated By: ${user?.name || 'Authorized User'}`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `settlement-receipt.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    addHistoryEvent('Receipt Downloaded', `Settlement receipt downloaded for payment of Rs. ${amountStr}`);
  };

  const pending = settlements.filter((item) => item.status !== 'PAID').length;

  return (
    <div className="stack-gap-lg">
      <div className="page-header">
        <h1>Debt Settlement</h1>
        <button 
            className="btn btn-primary" 
            disabled={tripLocked || pending > 0 || !selectedGroupId} 
            onClick={lockTrip}
        >
          {tripLocked ? 'Trip Locked' : 'Activate Trip Lock'}
        </button>
      </div>
      <div className="settlement-layout">
        <SettlementSummary rows={settlements} tripLocked={tripLocked} />
        <SettlementTable
          rows={settlements}
          onMarkPaid={markPaid}
          onDownloadReceipt={downloadReceipt}
          disabled={tripLocked}
        />
      </div>
    </div>
  );
};

export default SettlementPage;
