spring.application.name=backend
server.port=8080

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/tems_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=PARK@sik2023
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Allows Hibernate to automatically create/update tables defined by our Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SECURITY / CORS CONFIGURATION
# ===============================
# Allowing frontend connections from Vite
frontend.url=http://localhost:5173
